### ISSUE TITLE
Wrong index in pf_res_plotly.py

### ISSUE THREAD

**Issue by WinfriedL** [lthurner/pandapower#109]
The function `pf_res_plotly` uses the wrong index when generating the hoverinfo for the bus traces:

https://github.com/lthurner/pandapower/blob/4162a7d5ca8d7406c9217f744fd015d31a4bea7d/pandapower/plotting/plotly/pf_res_plotly.py#L91-L101

I am pretty sure it should be `net.bus.index` in line 93.

**Comment by FlorianShepherd** [comment]
That is indeed correct. Thank you WinfriedL for pointing that out :)
