### ISSUE TITLE
Size of Ybus

### ISSUE THREAD

**Issue by ManuelMBaumann** [lthurner/pandapower#112]
Dear all,

I am working on [this example](https://pandapower.readthedocs.io/en/v1.5.1/_images/cigre_network_mv.png) and I would like to extract the corresponding admittance matrix `Ybus`. I am using a convertion to pypower using this code snippet:

`net = ppconv.to_ppc(ppc)`
`baseMVA, bus, branch = net["baseMVA"], net["bus"], net["branch"]`
`Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)`

A spy plot of `Ybus` then gives: 
![makey-spy](https://user-images.githubusercontent.com/4333413/41773148-52079720-761b-11e8-998c-50c2d061baa5.png)

This particular example has `15 buses` and `18 loads`, and I would therefore expect the admittance matrix to be 15 times 15. From the connectivity of the network, I understand well the upper-left 15x15 block of the spy-plot above. But can someone please explain to me the entries in the last three rows and last three columns?

**Comment by ManuelMBaumann** [comment]
Here you can see the result of a power flow eqn. solve:

![ex-ybus-result](https://user-images.githubusercontent.com/4333413/41773405-41ed0c3e-761c-11e8-9c58-9b06b6b51470.png)

**Comment by ascheidl** [comment]
Hi,

in the network are three open line-bus switches, so pandapower internally creates three auxillary buses. See http://pandapower.readthedocs.io/en/v1.5.1/elements/switch.html#electric-model

Cheers,
Alex
