### ISSUE TITLE
tests fail with numpy 1.12

### ISSUE THREAD

**Issue by jhmenke** [lthurner/pandapower#13]
A deprecated warning from numpy < 1.12 has turned into an error.
Pypower files need to be fixed for this.

**Comment by FlorianShepherd** [comment]
At least for the powerflow calculation I would suggest to integrate the remaining files into pandapower and fix them.

Another alternative would be to fix pypower or hoping for a new release

**Comment by friederikemeier** [comment]
For the Opf we plan to fix it directly and send a pull request to pypower.
For the Pf we plan to fix it in our repo only, as the pf has already diverged a lot from the pypower pf.
