### ISSUE TITLE
Pandapower diagnosic nominal_voltages_dont_match fails

### ISSUE THREAD

**Issue by jatha** [lthurner/pandapower#14]
When i use `pandapower.diagnostic` on a Net with a 400kv bus and a 380kv bus with a Transformer in between, I get the warning, that the hv and lv side of the transformer are swapped.

**Comment by lthurner** [comment]
setting the parameter nom_voltage_tolerance in the diagnostic function to zero should probably get rid of  this problem. This should however be implemented better so that this problem doesn't occurr...

**Comment by julffers** [comment]
Thanks for reporting that issue. Should be fixed now. Please keep us posted if your problem still occurs. The workaround suggested by @lthurner also should be working, though.
