### ISSUE TITLE
OPF tests fail if connectivity check = True

### ISSUE THREAD

**Issue by FlorianShepherd** [lthurner/pandapower#43]
I removed the non-numba version of the connectivity check, since the reverse lookup (ppc2pd) is not unambiguously. So connectivity check is only available if numba is installed.

Now the OPF tests fail if check_connectivity=True -> I changed the default parameter for check_connectivty to False in runopp()

@friederikemeier could you check what the problem is?

**Comment by friederikemeier** [comment]
Will check on this later this week, I guess it is because the lookup tables are different for the opf.

**Comment by friederikemeier** [comment]
But shouldn't numba be installed anyways? I can't even import pandapower without having numba installed.
