### ISSUE TITLE
Converting data to Pandapower format

### ISSUE THREAD

**Issue by Kecib** [lthurner/pandapower#64]
Hi all,
I got a question regarding the possibility to convert network data form commercial software like Neplan or PSS Sincal into the Pandapower format. Is there any possibility to do so or is it necessary to do it manually recreating the networks? Help is appreciated :)

Greetings

**Comment by lthurner** [comment]
Yes it is possible to convert network data automaticallly. Converters from Sincal, PowerFactory, Neplan and more are however not part of the open source package, but only available under a commercially licensed pandapower pro package.

If you want to write such a converter yourself, there is a tutorial where a more complex network is created [here](https://github.com/lthurner/pandapower/blob/develop/tutorials/create_advanced.ipynb). The element information from which the network is created is saved in csv files [here](https://github.com/lthurner/pandapower/tree/develop/tutorials/example_advanced). So you have to read in the data from an interface that is available in your tool and automatically create the network using pandapower create functions. For example with PSS Sincal there is a access database that holds the network information, which can be read into python and used to built the pandapower network.
