### ISSUE TITLE
State estimation problem when using pandapower

### ISSUE THREAD

**Issue by hantongeee** [lthurner/pandapower#65]
I am using pandapower to solve the state estimation model, but I can't get the reasonable SE results for the IEEE-14 bus system. The python code is as follows:
import pandapower as pp
import pandapower.networks as pn
from pandapower.estimation import estimate
import numpy as np

net = pn.case14()
pp.runpp(net)
for i in net.bus.index:
    pp.create_measurement(net, "v", "bus", net.res_bus.vm_pu[i] * (np.random.random()*0.01 + 1), .01, i)
    pp.create_measurement(net, "p", "bus", net.res_bus.p_kw[i] * (np.random.random()*0.01 + 1), .01, i)
    pp.create_measurement(net, "q", "bus", net.res_bus.q_kvar[i] * (np.random.random()*0.01 + 1), .01, i)
for i in net.line.index:
    pp.create_measurement(net, "p", "line", net.res_line.p_from_kw[i] * (np.random.random()*0.01 + 1), net.res_line.p_from_kw[i] * 0.01, bus=net.line.from_bus[i], element=i)
    pp.create_measurement(net, "q", "line", net.res_line.q_from_kvar[i] * (np.random.random()*0.01 + 1), net.res_line.q_from_kvar[i] * 0.01, bus=net.line.from_bus[i], element=i)
   
success = estimate(net,init='flat')

And after running the above code, it can be found that the SE results are largely different from the power flow results. So could you please help me to find out what is wrong with my program? Thanks a lot.

**Comment by tyua321** [comment]
Hi, did you solve the problem? The error is my 14-bus is also large.
