### ISSUE TITLE
Keep J after power flow

### ISSUE THREAD

**Issue by lthurner** [lthurner/pandapower#68]
J is sometimes needed after a power flow for voltage stability studies. @FlorianShepherd  put together a tutorial on how it can be retrieved: https://github.com/lthurner/pandapower/blob/develop/tutorials/advanced/get_Ybus_and_J.ipynb
That is however quite some effort to reconstruct something that was already constructed and discarded just a few lines of code before. Is there any reason against giving an option to keep the last J from the powerflow?

**Comment by friederikemeier** [comment]
With my next commit you can acces J after a newton pf (lgorithm = "nr" , default) like this:

```
    pp.runpp(net)
    J_intern = net._ppc["internal"]["J"]
```

**Comment by lthurner** [comment]
I also added a tutorial on how to access ppc, Ybus and J and how to use the mappings for bus indices:
