### ISSUE TITLE
Estimation results are not written correctly

### ISSUE THREAD

**Issue by jhmenke** [lthurner/pandapower#71]
The fields "res_sgen_est" and "res_load_est" are not written correctly. Possibly even "res_gen_est" is affected.

This should be fixed and tests written accordingly.

**Comment by jhmenke** [comment]
The erroneous results are deleted for now (refactoring moved to #48), the other results res_bus_est, res_line_est, res_trafo_est are now tested.

**Comment by lthurner** [comment]
commit 59ed1fddf279b54e7f3301dc5fd646516ca2a7bf
