### ISSUE TITLE
simple_plotly doesn't plot network according to matrices

### ISSUE THREAD

**Issue by mihagibson** [lthurner/pandapower#75]
Hi!
I use Jupyter notebooks.
The code below is from the website and it is supposed to plot the MV network. But when I run the code below the network that is plotted is not the same as the one that I wanted to plot (from the website).
And also the network plotted with simple_plotly() does not correspond to the bus, line and trafos matrices. So the plotted network is not plotted as it is supposed to be. Please see the attached picture.

![napaka_pp_1](https://user-images.githubusercontent.com/24324694/31437478-ad95ffd6-ae85-11e7-9e2b-716e1e32c45e.png)

net_mv = pn.create_cigre_network_mv(with_der=False)
simple_plotly(net_mv)

**Comment by jhmenke** [comment]
The plot is correct, i suspect that only the labels are set incorrectly.

**Comment by jhmenke** [comment]
This was just a small bug with incorrectly ordered bus_geodata. It will be fixed in commit f316742fc15f6162fc.

**Comment by mihagibson** [comment]
Thank u for your answer, but I am not used to github. So is it possible to download the whole cigre_networks.py and synthetic_voltage_control_lv_networks.py scripts?

or do I have to change them by myself?

**Comment by lthurner** [comment]
You can install the current version from github by uninstall pandapower:

> pip uninstall pandapower

And then installing the newest develop version of pandapower from github:

> pip install git+https://github.com/lthurner/pandapower.git@develop

It will take a while to install because the repo is cloned into, but in the end you should have the newest version.

**Comment by mihagibson** [comment]
I uninstalled it, then when I try to install it I get this:

Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/lthurner/pandapower.git C:\Users\Miha\AppData\Local\Temp\pip-7s8t_zo7-build
Cannot find command 'git'

**Comment by lthurner** [comment]
you have to install git: https://git-scm.com/

**Comment by mihagibson** [comment]
I 've installed, buses are now OK but lines are still wrong.
Switch table also doesn't correspond to the plot.

**Comment by jhmenke** [comment]
I checked it again and you are correct. Maybe the author @jkrstulo can identify the problem the fastest?

**Comment by FlorianShepherd** [comment]
The error is now fixed I assume. See https://github.com/lthurner/pandapower/commit/f14386ceccd21ae24a2e51962767aced7a8fd80e 

 @mihagibson would you confirm that, please?

Also note that the legend in simple_plotly is a little bit strange atm. We'll have a look into that soon.
