### ISSUE TITLE
Error in plotting.simple_plot()

### ISSUE THREAD

**Issue by basemidlbi** [lthurner/pandapower#81]
Hi Leon,

the simple plotting in pandapower (without coordinates) does not work.
I think the module igraph does not work, and you need to use jgraph instead.
Using the module networkx give an error as well. I wrote these simple commands to test simple_plot():

import pandapower.networks as ppn
kerber = ppn.create_kerber_dorfnetz(p_load_in_kw=6.)
import pandapower.plotting as ppl
ppl.simple_plot(kerber, library="igraph")

**Comment by lthurner** [comment]
The commands as you put them plots the network like this for me:
![grafik](https://user-images.githubusercontent.com/23637821/32942019-02a1755e-cb88-11e7-8565-de09b3dd5033.png)
So it does work with the right installation.

You need to install python-igraph (not igraph), which also needs pycairo.  Compiled wheels for both packages can be found on Christoph Gohlkes site: https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by basemidlbi** [comment]
Hi Leon,
thanks for the fast reply. It works well after installing pycairo.
Best regards, Basem

**Comment by lthurner** [comment]
You are welcome Basem!
