### ISSUE TITLE
runpp test fails

### ISSUE THREAD

**Issue by saruman1970** [lthurner/pandapower#90]
Hello. I've installed python from scrath and then installed pandapower with two different Pc, one with winx32 ant the other with winx64.
When I run the test suit, one test fails every time

============================= test session starts =============================
platform win32 -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
.
.
pandapower\test\loadflow\test_runpp.py ...................x....... 
.
=================== 264 passed, 1 xfailed in 247.62 seconds ===================

I don't know if there is some other log file to  check

**Comment by lthurner** [comment]
Hi, this test is marked as xfailed, which means its expected to fail (see pytest documentation). It is a (minor) known bug that is not fixed yet. Your installation is working fine!
