### ISSUE TITLE
DC state estimation

### ISSUE THREAD

**Issue by fhdummy** [lthurner/pandapower#95]
Hello,

as of now, I cannot see a way, to easily conduct a DC state estimation (e.g. via an additional parameter in the function `pandapower.estimation.estimate`).

Will this be added in the future, or is there an easy way to do a DC state estimation using the currently existing code?

Thanks.

**Comment by jhmenke** [comment]
Hello fhdummy,
the DC state estimation model is not implemented right now. It is not planned, but contributions are always welcome!
I think it would be relatively straight-forward to implement. The functions create_jacobian and create_hx can be reimplemented with the simpler DC model, many some minor changes have to be made to the rest of the code as well.
